### ISSUE TITLE
Kindly suggest to avoid using lieslint-disable

### ISSUE THREAD

**Issue by Alejandroq12** [smunoz1988/toDoList#3]
Hi there,

I took some time to review the TaskList class you shared, and overall, it looks great! Your code is well-structured and easy to understand. I have a few suggestions and improvements for you to consider:

ESLint warning in generateTaskHTML() method: There is an eslint warning in the generateTaskHTML() method. Instead of disabling eslint for this method, I recommend trying to address the warning to maintain consistency and best practices in your code.
https://github.com/smunoz1988/toDoList/blob/AddRemoveEdit/src/modules/functionality.js#L10-L21

Please let me know if you have any questions or need more clarification on any of these points. Great work on this , and I look forward to seeing your future improvements!

Best regards,

**Comment by smunoz1988** [comment]
Julio, thanks for your Feedback! 

Issue fix!! 

Have a great day!

**Comment by smunoz1988** [comment]
Close issue!
